export const TV_GENRES = [
  { label: '全部', value: 'all' },
  { label: '剧情', value: '剧情' },
  { label: '喜剧', value: '喜剧' },
  { label: '爱情', value: '爱情' },
  { label: '悬疑', value: '悬疑' },
  { label: '武侠', value: '武侠' },
  { label: '古装', value: '古装' },
  { label: '家庭', value: '家庭' },
  { label: '犯罪', value: '犯罪' },
  { label: '科幻', value: '科幻' },
  { label: '恐怖', value: '恐怖' },
  { label: '历史', value: '历史' },
  { label: '战争', value: '战争' },
  { label: '动作', value: '动作' },
  { label: '冒险', value: '冒险' },
  { label: '传记', value: '传记' },
  { label: '奇幻', value: '奇幻' },
  { label: '惊悚', value: '惊悚' },
  { label: '灾难', value: '灾难' },
  { label: '歌舞', value: '歌舞' },
  { label: '音乐', value: '音乐' },
];

export const SHOW_GENRES = [
  { label: '全部', value: 'all' },
  { label: '真人秀', value: '真人秀' },
  { label: '脱口秀', value: '脱口秀' },
  { label: '音乐', value: '音乐' },
  { label: '歌舞', value: '歌舞' },
];

export const TV_REGIONS = [
  { label: '全部', value: 'all' },
  { label: '华语', value: '华语' },
  { label: '欧美', value: '欧美' },
  { label: '国外', value: '国外' },
  { label: '韩国', value: '韩国' },
  { label: '日本', value: '日本' },
  { label: '中国大陆', value: '中国大陆' },
  { label: '中国香港', value: '中国香港' },
  { label: '美国', value: '美国' },
  { label: '英国', value: '英国' },
  { label: '泰国', value: '泰国' },
  { label: '中国台湾', value: '中国台湾' },
  { label: '意大利', value: '意大利' },
  { label: '法国', value: '法国' },
  { label: '德国', value: '德国' },
  { label: '西班牙', value: '西班牙' },
  { label: '俄罗斯', value: '俄罗斯' },
  { label: '瑞典', value: '瑞典' },
  { label: '巴西', value: '巴西' },
  { label: '丹麦', value: '丹麦' },
  { label: '印度', value: '印度' },
  { label: '加拿大', value: '加拿大' },
  { label: '爱尔兰', value: '爱尔兰' },
  { label: '澳大利亚', value: '澳大利亚' },
];

export const TV_YEARS = [
  { label: '全部', value: 'all' },
  { label: '2025', value: '2025' },
  { label: '2024', value: '2024' },
  { label: '2023', value: '2023' },
  { label: '2022', value: '2022' },
  { label: '2021', value: '2021' },
  { label: '2020', value: '2020' },
  { label: '2019', value: '2019' },
  { label: '2010年代', value: '2010s' },
  { label: '2000年代', value: '2000s' },
  { label: '90年代', value: '1990s' },
  { label: '80年代', value: '1980s' },
  { label: '70年代', value: '1970s' },
  { label: '60年代', value: '1960s' },
  { label: '更早', value: 'earlier' },
];

export const TV_SORTS = [
  { label: '综合排序', value: 'T' },
  { label: '近期热度', value: 'U' },
  { label: '首播时间', value: 'R' },
  { label: '高分优先', value: 'S' },
];
